# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PillBuddyNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PillBuddyNative

  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'

end
